vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        recipe:
            uri_prefix: /images/recette
            upload_destination: '%kernel.project_dir%/public/images/recette'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            
            